import Head from 'next/head'
import { Inter } from 'next/font/google'
import Login from './login'
import Header from './components/Header'
import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  const router = useRouter();
  useEffect(() => {
    const storedData = localStorage.getItem('token');
    if (!storedData) {
      const redirectTimer = setTimeout(() => {
        router.push('/login'); // Replace '/destination-page' with your target page path
      }, 3000);
    }

  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login></Login>
    </>
  )
}
